### ISSUE TITLE
Adding a new fingerprint throws an IllegalBlockSizeException

### ISSUE THREAD

**Issue by shnobee** [square/whorlwind#26]
I implemented this library a while back and it has been working well until the Android O update. Editing the fingerprint data i.e adding a new fingerprint throws an IllegalBlockSizeException. I have tested this on the sample app as well and the same exception is thrown. It seems to be happening when Cipher.doFinal() is called. 

I have tested this on multiple operating systems and this seems to be a problem introduced in android 8.0 and fixed in 8.1. A lot of devices are still unable to upgrade to 8.1, is there a workaround/fix for this?

`04-12 09:06:55.785 21711-21711/com.squareup.whorlwind.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.squareup.whorlwind.sample, PID: 21711
                                                                               io.reactivex.exceptions.OnErrorNotImplementedException
                                                                                   at io.reactivex.internal.functions.Functions$14.accept(Functions.java:229)
                                                                                   at io.reactivex.internal.functions.Functions$14.accept(Functions.java:226)
                                                                                   at io.reactivex.internal.observers.LambdaObserver.onError(LambdaObserver.java:72)
                                                                                   at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.checkTerminated(ObservableObserveOn.java:276)
                                                                                   at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:172)
                                                                                   at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                                                   at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                                   at android.os.Handler.handleCallback(Handler.java:789)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                Caused by: javax.crypto.IllegalBlockSizeException
                                                                                   at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
                                                                                   at javax.crypto.Cipher.doFinal(Cipher.java:1736)
                                                                                   at com.squareup.whorlwind.FingerprintAuthOnSubscribe$2.onAuthenticationSucceeded(FingerprintAuthOnSubscribe.java:142)
                                                                                   at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedSucceeded(FingerprintManager.java:1005)
                                                                                   at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:926)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                   at android.os.Looper.loop(Looper.java:164) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6809) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                                                                                Caused by: android.security.KeyStoreException: Key user not authenticated
                                                                                   at android.security.KeyStore.getKeyStoreException(KeyStore.java:695)
                                                                                   at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:132)
                                                                                   at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:217)
                                                                                   at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
                                                                                   at javax.crypto.Cipher.doFinal(Cipher.java:1736) 
                                                                                   at com.squareup.whorlwind.FingerprintAuthOnSubscribe$2.onAuthenticationSucceeded(FingerprintAuthOnSubscribe.java:142) 
                                                                                   at android.hardware.fingerprint.FingerprintManager$MyHandler.sendAuthenticatedSucceeded(FingerprintManager.java:1005) 
                                                                                   at android.hardware.fingerprint.FingerprintManager$MyHandler.handleMessage(FingerprintManager.java:926) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                                   at android.os.Looper.loop(Looper.java:164) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6809) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) `

**Comment by mattprecious** [comment]
Fixed in #27
