### ISSUE TITLE
NullPointerException FingerprintManager on 

### ISSUE THREAD

**Issue by marlonbosse** [square/whorlwind#28]
I see currently a crash that is only happening on a specific device where `isHardwareDetected()` throws a `NullPointerException`. 

My proposal would be to check if `FingerprintManager == null` and return NullWhorlwind. Shall I create a pull request?

Device details: 
```
Android: 8.0.0
Android Build: 48.1.A.0.129
Manufacturer: Sony
Model: G3121
Thread: main-2
```

Stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.hardware.fingerprint.FingerprintManager.isHardwareDetected()' on a null object reference
	at com.squareup.whorlwind.RealWhorlwind.canStoreSecurely(RealWhorlwind.java:77)
	at com.moovel.pay.fingerprint.WhorlwindFingerprintStorage.canStoreSecurely(WhorlwindFingerprintStorage.java:25)
	at com.moovel.pay.screens.pin.RequestPinPresenter.onStart(RequestPinPresenter.java:57)
	at com.moovel.mvp.PresenterLifecycleObserver.onStart(PresenterLifecycleObserver.java:57)
	at com.moovel.mvp.CompositeLifecycleObserver.onStart(CompositeLifecycleObserver.java:50)
	at com.moovel.mvp.DaggerMVPFragment.onStart(DaggerMVPFragment.java:1049)
	at android.support.v4.app.Fragment.performStart(Fragment.java:2287)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1458)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
	at android.os.Handler.handleCallback(Handler.java:869)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:206)
	at android.app.ActivityThread.main(ActivityThread.java:6749)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)```

**Comment by mattprecious** [comment]
Oh, yes!
